<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ include file="/WEB-INF/views/common/header.jsp" %>

<h1 class="page-title"><span class="icon">&#128202;</span> Books &amp; Authors Report</h1>

<div class="alert alert-info">
    &#128161; This report is generated by a custom JPQL <strong>INNER JOIN</strong> query between the
    <code>books</code> and <code>authors</code> tables, returning a combined projection DTO.
</div>

<div class="card">
    <div class="card-header">
        <span class="card-title">Inner Join Results (${report.size()} records)</span>
        <a href="${pageContext.request.contextPath}/books" class="btn btn-secondary btn-sm">&#8592; Back to Books</a>
    </div>
    <div class="table-wrapper">
        <table class="report-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Book Title</th>
                    <th>ISBN</th>
                    <th>Year</th>
                    <th>Genre</th>
                    <th>Author Name</th>
                    <th>Author Nationality</th>
                </tr>
            </thead>
            <tbody>
                <c:choose>
                    <c:when test="${empty report}">
                        <tr><td colspan="7" style="text-align:center;padding:2rem;color:#999;">No data found.</td></tr>
                    </c:when>
                    <c:otherwise>
                        <c:forEach var="row" items="${report}" varStatus="status">
                            <tr>
                                <td>${status.count}</td>
                                <td><strong>${row.bookTitle}</strong></td>
                                <td><code>${row.isbn}</code></td>
                                <td>${row.publicationYear}</td>
                                <td><span class="badge badge-genre">${row.genre}</span></td>
                                <td>${row.authorName}</td>
                                <td><span class="badge badge-nation">${row.authorNationality}</span></td>
                            </tr>
                        </c:forEach>
                    </c:otherwise>
                </c:choose>
            </tbody>
        </table>
    </div>
</div>

<div class="card" style="background:#f8f9fa;border:1px dashed #c5cae9;">
    <div class="card-title" style="margin-bottom:.75rem;">JPQL Query Used</div>
    <pre style="background:#1a237e;color:#e8eaf6;padding:1rem 1.2rem;border-radius:6px;font-size:.85rem;overflow-x:auto;">SELECT new com.library.dto.BookWithAuthorDTO(
    b.id, b.title, b.isbn, b.publicationYear, b.genre,
    a.name, a.nationality
)
FROM Book b
INNER JOIN b.author a
ORDER BY a.name, b.title</pre>
</div>

<%@ include file="/WEB-INF/views/common/footer.jsp" %>
